attachment operation files to local storage
Shkuryn/finance_tracker pull request #33
Opened 2022-05-27 21:50 UTC by Ikl0

2022-05-29 07:13 UTC, VitalyKadyrko submitted a review, later dismissed

2022-05-29 10:52 UTC, VitalyKadyrko commented
Resolve conflict please

2022-06-02 17:50 UTC, closed without merging

2022-06-02 17:54 UTC, Shkuryn requested changes

2022-06-02 17:54 UTC, Shkuryn commented on config/storage.yml
> +  access_token: "sl.BIu3nNYTdJFyX5frR_blkWP9X3EGI9FiS9ZppDjqvTxthi2OZ3pGokuKCq5EFEizROf3CpRY-jDl4VwUy8N7O9oj_FUESmKIx729Njaw5d4tU9dPNOE-_4Pr2N3lOEVtdsnIp5NNaoXJ"
It's dangerous to commit this info. Try to store this other way.